---
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    # Must match webpack.config.js
    presets: ["@babel/preset-env", "@babel/preset-react"]
env:
  browser: true
extends: ["airbnb", "airbnb/hooks", "plugin:react/recommended", "prettier"]
plugins: [import, react, react-hooks]
settings:
  import/resolver: webpack
  react:
    version: detect
rules:
  camelcase: off
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/control-has-associated-label: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  react/jsx-wrap-multilines: 0
  react/jsx-one-expression-per-line: 0
  no-param-reassign: 0
  react/jsx-curly-newline: 0
  default-param-last: 0
  react/function-component-definition: 0
