repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        pass_filenames: true
        exclude: baselayer|node_modules|static
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 6ba454799f284b13ccd53ca2adaf4848da6d3509 # v0.0.240
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 50c5478ed9e10bf360335449280cf2a67f4edb7a # v2.7.1
    hooks:
      - id: prettier
        exclude: ".*config.yaml"
  - repo: local
    hooks:
      - id: ESLint
        name: ESLint
        entry: npx eslint -c eslint.config.js static/js --fix
        language: system
        files: \.[j]sx?$
        exclude: 'eslint.config.js|rspack.config.js'
        types: [file]
